In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import ast # Used to safely evaluate string representations of Python literals
import os

In [16]:
#Read in all the data from the processed chunks
output_dir = "../data_aquisition/processed_chunks"

import glob

# Find all the processed chunk CSV files
chunk_files = glob.glob(os.path.join(output_dir, "*.csv"))

# Read each chunk file into a list of dataframes
df_list = [pd.read_csv(f) for f in chunk_files]

# Concatenate all dataframes in the list into one
df = pd.concat(df_list, ignore_index=True)

In [3]:
#Look at the first few rows of the DataFrame
df.head()

,Name,Designer,ID,URL,Free,Photo,Craft,Attributes,Gauge,Difficulty Average,Downloadable,Gauge Divisor,Gauge Pattern,Pattern Type,Yarn Weight,Projects Count,Rating Average,Sizes Available,Photos
0,#08 Cropped Cardigan,Faye Rubenstein,18699,https://www.ravelry.com/patterns/library/08-cr...,False,https://images4-a.ravelrycache.com/uploads/rrr...,Knitting,"['female', 'adult', 'petite', 'textured', 'sad...",28.0,3.666667,True,4.0,textured stitch,cardigan,DK,8,0.000000,"Bust: 30 (33, 36, 40)""/76 (84, 91.5, 101.5)cm","[{'id': 10982458, 'sort_order': 1, 'user_id': ..."
1,Maybelline,Louisa Harding,18700,https://www.ravelry.com/patterns/library/maybe...,False,https://images4-a.ravelrycache.com/uploads/kew...,Knitting,"['female', 'adult', 'fitted', 'seamed', 'shawl...",22.0,0.000000,False,4.0,over pattern using US 6 (4.00 mm) needles.,cardigan,DK,3,0.000000,Small (Medium),"[{'id': 823680, 'sort_order': 1, 'user_id': 31..."
2,Flo,Kim Hargreaves,18721,https://www.ravelry.com/patterns/library/flo,False,https://images4-f.ravelrycache.com/flickr/4/1/...,Knitting,"['female', 'adult', 'seamed', 'ruffles', 'butt...",28.0,4.076923,False,4.0,NaN,cardigan,Fingering,58,4.583333,XS (32); S (34); M (36); L (38); XL (40); XXL ...,"[{'id': 10573288, 'sort_order': 1, 'user_id': ..."
3,Baby's First Merino Sweater,Morehouse Designs,18725,https://www.ravelry.com/patterns/library/babys...,False,https://images4-a.ravelrycache.com/uploads/Cha...,Knitting,"['unisex', 'baby', 'ribbed', 'textured', 'crew...",NaN,2.600000,False,NaN,NaN,baby,Worsted,16,4.600000,NaN,"[{'id': 331059, 'sort_order': 1, 'user_id': 64..."
4,Honeycomb Cardigan,Rosemary Drysdale,18779,https://www.ravelry.com/patterns/library/honey...,False,https://images4-f.ravelrycache.com/flickr/3/2/...,Knitting,"['female', 'adult', 'cables', 'ribbed', 'seame...",20.0,0.000000,False,4.0,2x2 rib,cardigan,Aran,4,0.000000,NaN,"[{'id': 5850319, 'sort_order': 1, 'user_id': 9..."

In [4]:
#Look at the last few rows of the DataFrame
df.tail()

,Name,Designer,ID,URL,Free,Photo,Craft,Attributes,Gauge,Difficulty Average,Downloadable,Gauge Divisor,Gauge Pattern,Pattern Type,Yarn Weight,Projects Count,Rating Average,Sizes Available,Photos
39792,Meader,Åsa Buchta,7352049,https://www.ravelry.com/patterns/library/meader,False,https://images4-a.ravelrycache.com/uploads/mjk...,Knitting,"['adult', 'plus', 'lace', 'seamed', 'v-neck', ...",15.0,0.0,True,4.0,Pattern stitch,cardigan,Bulky,5,0.0,"Bust (with buttonbands overlapped): (38½, 42¾,...","[{'id': 131120686, 'sort_order': 1, 'user_id':..."
39793,Yonagi,Hiromi Otsuru,7354596,https://www.ravelry.com/patterns/library/yonagi,False,https://images4-a.ravelrycache.com/uploads/ami...,Knitting,"['adult', 'ribbed', 'top-down', 'cropped', 'wo...",22.0,0.0,False,4.0,in Stockinette stitch,cardigan,Sport,6,0.0,"Finished bust measurements: 1 (2, 3, 4) (5, 6,...","[{'id': 131374067, 'sort_order': 1, 'user_id':..."
39794,Sazanami,Megumi Sawada,7354602,https://www.ravelry.com/patterns/library/sazan...,False,https://images4-a.ravelrycache.com/uploads/ami...,Knitting,"['adult', 'cables', 'crew-neck', 'buttoned', '...",18.0,0.0,False,4.0,in Stockinette stitch,cardigan,DK,3,0.0,"Finished bust measurements: 1 (2, 3, 4) (5, 6,...","[{'id': 131374122, 'sort_order': 1, 'user_id':..."
39795,Ayaka,Linda Marveng,7355593,https://www.ravelry.com/patterns/library/ayaka-4,False,https://images4-a.ravelrycache.com/uploads/lin...,Knitting,"['female', 'adult', 'plus', 'cables', 'eyelets...",25.0,0.0,True,4.0,St st,cardigan,Sport,7,0.0,"1 (2, 3, 4, 5) (6, 7, 8, 9)","[{'id': 131460405, 'sort_order': 1, 'user_id':..."
39796,Patch Me Up,Candi Jensen,7357106,https://www.ravelry.com/patterns/library/patch...,True,https://images4-a.ravelrycache.com/uploads/amy...,Knitting,"['unisex', 'adult', 'oversized', 'seamed', 'bo...",20.0,0.0,True,4.0,Stockinette,cardigan,Worsted,6,0.0,"XS[S, M, L, 1X, 2X, 3X, 4X, 5X]","[{'id': 131580801, 'sort_order': 1, 'user_id':..."

In [5]:
#Get a summary of the DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39797 entries, 0 to 39796
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                39797 non-null  object
 1   Designer            39797 non-null  object
 2   ID                  39797 non-null  int64
 3   URL                 39797 non-null  object
 4   Free                39796 non-null  object
 5   Photo               39797 non-null  object
 6   Craft               39793 non-null  object
 7   Attributes          39797 non-null  object
 8   Gauge               37341 non-null  float64
 9   Difficulty Average  39793 non-null  float64
 10  Downloadable        39796 non-null  object
 11  Gauge Divisor       37549 non-null  float64
 12  Gauge Pattern       32392 non-null  object
 13  Pattern Type        39792 non-null  object
 14  Yarn Weight         38817 non-null  object
 15  Projects Count      39797 non-null  int64
 16  Rating Average      39793 non-null  float64
 17  Sizes Available     34796 non-null  object
 18  Photos              39793 non-null  object
dtypes: float64(4), int64(2), object(13)
memory usage: 5.8+ MB

In [6]:
#Get a count of unique values in each column -- based on this, I can see that Sizes Available isn't going to be very useful since it has a lot of unique values, but, it will be useful when it comes to the final app since it tells us what sizes are available for each pattern
df.nunique()

Name                  37138
Designer               6015
ID                    39797
URL                   39797
Free                      2
Photo                 39796
Craft                     1
Attributes            38453
Gauge                   161
Difficulty Average     4364
Downloadable              2
Gauge Divisor             3
Gauge Pattern          9305
Pattern Type             20
Yarn Weight              15
Projects Count         1205
Rating Average         3023
Sizes Available       19491
Photos                39793
dtype: int64

In [7]:
#Check for missing values -- I'm not sure yet if I'm going to use Gauge as a feature, so I might need to do something about the missing values in that column later
df.isnull().sum()

Name                     0
Designer                 0
ID                       0
URL                      0
Free                     1
Photo                    0
Craft                    4
Attributes               0
Gauge                 2456
Difficulty Average       4
Downloadable             1
Gauge Divisor         2248
Gauge Pattern         7405
Pattern Type             5
Yarn Weight            980
Projects Count           0
Rating Average           4
Sizes Available       5001
Photos                   4
dtype: int64

In [8]:
# Use .isin() to check for multiple values at once
# Get only pullovers and cardigans
df = df[df['Pattern Type'].isin(['pullover', 'cardigan'])]

In [9]:
df['Attributes_list'] = df['Attributes'].fillna('[]').apply(ast.literal_eval)

# Create a new DataFrame with dummy variables from the 'Attributes_list'
# We first explode the lists to have one attribute per row, then get dummies
# and finally group by the original index and sum to get the one-hot encoding
attributes_dummies = df['Attributes_list'].explode().str.get_dummies().groupby(level=0).sum()

# Add a prefix to the attribute columns to avoid potential column name conflicts
attributes_dummies = attributes_dummies.add_prefix('attr_')

# Concatenate the new dummy variables DataFrame with the original DataFrame
df_expanded = pd.concat([df, attributes_dummies], axis=1)

# Drop the intermediate 'Attributes_list' and original 'Attributes' columns
df_expanded = df_expanded.drop(['Attributes', 'Attributes_list'], axis=1)

In [10]:
# Now, filter the DataFrame to include only rows where 'attr_adult' is True
df_expanded = df_expanded[df_expanded['attr_adult'] == True]

df_expanded.shape

(24816, 233)

In [12]:
df['Pattern Type'].value_counts()

Pattern Type
pullover    16712
cardigan    13942
Name: count, dtype: int64

In [11]:
   # Get all the columns that start with 'attr_'
attribute_columns = [col for col in df_expanded.columns if col.startswith('attr_')]

# Calculate the sum of each attribute column
attribute_counts = df_expanded[attribute_columns].sum()

# Create a new DataFrame from the attribute counts
attribute_counts_df = pd.DataFrame(attribute_counts, columns=['Count'])

# Reset the index to make the attribute names a column
attribute_counts_df = attribute_counts_df.reset_index().rename(columns={'index': 'Attribute'})

# Sort the attributes by count in descending order
attribute_counts_df = attribute_counts_df.sort_values(by='Count', ascending=False)

# Remove the 'attr_' prefix from the 'Attribute' column
attribute_counts_df['Attribute'] = attribute_counts_df['Attribute'].str.replace('attr_', '')
attribute_counts_df.to_csv('attribute_counts.csv', index=False)